//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisProject.Models
{
    using System;
    using System.Collections.Generic;

    public partial class CAFV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAFV()
        {
            this.VehicleRegistrations = new HashSet<VehicleRegistration>();
        }

        public String CAFVId { get; set; }
        public string CAFVName { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleRegistration> VehicleRegistrations { get; set; }
    }
}
