//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VehicleRegistration
    {
        [Required]
        [Display(Name = "City Name")]
        public int CityId { get; set; }
        [Required]
        public int Zip { get; set; }
        [Required]
        [Display(Name = "Model Year")]
        public string ModelYear { get; set; }
        [Required]
        public string Make { get; set; }
        [Required]
        public string Model { get; set; }
        [Required]
        [Display(Name = "Vehicle Type")]
        public string VehicleType { get; set; }
        [Required]
        public string CAFV { get; set; }
        [Required]
        [Display(Name = "Range")]
        public int ElectricRange { get; set; }
        [Required]
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        [Required]
        [StringLength(2, MinimumLength = 2)]
        public string State { get; set; }
        [Required]
        [Display(Name = "Registration Id")]
        public string VehcileRegistrationId { get; set; }

        public virtual City City { get; set; }
    }
}
