//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleRegistration
    {
        public int CityId { get; set; }
        public int Zip { get; set; }
        public string ModelYear { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string VehicleType { get; set; }
        public string CAFV { get; set; }
        public int ElectricRange { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string State { get; set; }
        public string VehcileRegistrationId { get; set; }
    
        public virtual City City { get; set; }
    }
}
